"""BoardSession — spec-driven host access to a Red Pitaya feedback design.

Generalises the spin-controller's board_io.BoardSession: instead of a hand-kept
block of REG_* constants, it takes the *generated* registers module for the
design and resolves every access by register name. A persistent TCP connection
to the on-board daemon (daemon.py) keeps each access at ~1 ms.

    import registers_core as regs        # generated by regspec/gen_all.py
    with BoardSession("192.168.8.220", regs) as b:
        b.write("scratch", 0x1234)
        assert b.read("scratch") == 0x1234
        b.write_field("control", "dac_enable", 1)

Runs on the host PC (needs Python 3; the daemon on the board runs 3.5).
"""

from __future__ import print_function

import os
import socket
import subprocess
import time


def start_daemon(ip, port=9001, daemon_script=None):
    """SCP daemon.py to the board and launch it detached. Idempotent."""
    if daemon_script is None:
        daemon_script = os.path.join(os.path.dirname(os.path.abspath(__file__)), "daemon.py")
    subprocess.check_call(["scp", "-q", daemon_script, "root@{}:/tmp/rp_daemon.py".format(ip)])
    subprocess.call(["ssh", "root@{}".format(ip), "pkill -f rp_daemon.py"])
    time.sleep(0.2)
    subprocess.check_call(
        ["ssh", "-f", "root@{}".format(ip),
         "python3 /tmp/rp_daemon.py --port {} > /tmp/rp_daemon.log 2>&1".format(port)])
    time.sleep(0.3)


def stop_daemon(ip):
    subprocess.call(["ssh", "root@{}".format(ip), "pkill -f rp_daemon.py 2>/dev/null"])


class BoardSession(object):
    """Name-addressed AXI register + BRAM access to one board.

    `regs` is the generated registers module for the design (exposes REGISTERS,
    BASE_ADDRESS, and per-register/field constants).
    """

    def __init__(self, ip, regs, port=9001, start=True, daemon_script=None):
        self.ip = ip
        self.port = port
        self.regs = regs
        self._meta = regs.REGISTERS
        if start:
            start_daemon(ip, port, daemon_script)
        self.sock = socket.create_connection((ip, port), timeout=5.0)
        self.sock.settimeout(2.0)
        self.f = self.sock.makefile("rwb", buffering=0)
        if self._cmd("PING") != "PONG":
            raise RuntimeError("daemon at {} did not respond to PING".format(ip))
        if "magic" in self._meta and self.read("magic") != 0xDEADBEEF:
            raise RuntimeError("AXI bridge at {} not alive (magic mismatch)".format(ip))

    # --- low-level wire protocol (matches daemon.py) ---

    def _cmd(self, line):
        self.f.write((line + "\n").encode("ascii"))
        resp = self.f.readline().decode("ascii").strip()
        if resp.startswith("ERR"):
            raise RuntimeError("daemon: " + resp)
        return resp

    def _read_off(self, offset):
        return int(self._cmd("R {:x}".format(offset)), 16)

    def _write_off(self, offset, value):
        self._cmd("W {:x} {:x}".format(offset, value & 0xFFFFFFFF))

    # --- name-addressed API ---

    def _offset(self, name):
        try:
            return self._meta[name]["offset"]
        except KeyError:
            raise KeyError("no register named {!r} in this design".format(name))

    def read(self, name):
        """Read a register by name (returns the raw 32-bit word)."""
        return self._read_off(self._offset(name))

    def write(self, name, value):
        """Write a register by name. Refuses read-only registers."""
        if self._meta[name]["access"] != "rw":
            raise ValueError("register {!r} is read-only".format(name))
        self._write_off(self._offset(name), value)

    def read_signed(self, name, bits=32):
        v = self.read(name)
        if v & (1 << (bits - 1)):
            v -= 1 << bits
        return v

    def read_field(self, name, field):
        mask, shift = self._meta[name]["fields"][field]
        return (self.read(name) & mask) >> shift

    def write_field(self, name, field, value):
        """Read-modify-write one bitfield of an rw register."""
        mask, shift = self._meta[name]["fields"][field]
        word = self.read(name)
        self.write(name, (word & ~mask) | ((value << shift) & mask))

    def read_bram(self, offset, count):
        """Read `count` consecutive 32-bit words from a BRAM region."""
        words = self._cmd("RB {:x} {}".format(offset, count)).split()
        return [int(w, 16) for w in words]

    # --- lifecycle ---

    def close(self):
        for step in (lambda: self._cmd("QUIT"), self.f.close, self.sock.close):
            try:
                step()
            except Exception:
                pass

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()
