"""AUTO-GENERATED by regspec/generators/gen_python.py — DO NOT EDIT BY HAND.

Register map for 'spin_controller' (42 registers).
Regenerate with: python regspec/gen_all.py <spec>.yaml
"""

BASE_ADDRESS = 0x40000000
DATA_WIDTH = 32
ADDR_SPAN = 0x100

# --- register offsets (bytes from BASE_ADDRESS) ---
REG_CONTROL                      = 0x00
REG_BLINK_HALF_PERIOD            = 0x04
REG_SCRATCH                      = 0x08
REG_MAGIC                        = 0x0c
REG_NCO_TUNING_WORD              = 0x10
REG_NCO_AMPLITUDE                = 0x14
REG_CAPTURE_CTRL                 = 0x18
REG_CAPTURE_STATUS               = 0x1c
REG_FREQ_GATE_CYCLES             = 0x20
REG_FREQ_COUNT_RAW               = 0x24
REG_FREQ_THRESHOLD               = 0x28
REG_FREQ_COUNT_DEC               = 0x2c
REG_AMP_RAW                      = 0x30
REG_AMP_DEC                      = 0x34
REG_BUFFER_ENABLE                = 0x38
REG_BUFFER_WRITE_PTR             = 0x3c
REG_BUFFER_SAMPLE_COUNT          = 0x40
REG_BUFFER_DEPTH                 = 0x44
REG_PID_SETPOINT                 = 0x48
REG_PID_GAINS                    = 0x4c
REG_NCO_SHIFT                    = 0x50
REG_PID_OUTPUT                   = 0x54
REG_PID_STATUS                   = 0x58
REG_LOCK_STATUS                  = 0x5c
REG_LOCK_TARGET_TW               = 0x60
REG_LOCK_RAMP_RATE               = 0x64
REG_LOCK_CAPTURE_WIN             = 0x68
REG_SYNC_CONTROL                 = 0x6c
REG_ADC_SELECT                   = 0x70
REG_NCO_TUNING_WORD_B            = 0x74
REG_NCO_AMPLITUDE_B              = 0x78
REG_FREQ_COUNT_DEC_B             = 0x7c
REG_AMP_DEC_B                    = 0x80
REG_PID_SETPOINT_B               = 0x84
REG_PID_GAINS_B                  = 0x88
REG_NCO_SHIFT_B                  = 0x8c
REG_PID_OUTPUT_B                 = 0x90
REG_PID_STATUS_B                 = 0x94
REG_LOCK_STATUS_B                = 0x98
REG_LOCK_TARGET_TW_B             = 0x9c
REG_LOCK_RAMP_RATE_B             = 0xa0
REG_LOCK_CAPTURE_WIN_B           = 0xa4

# --- bitfields: (shift, mask) per field ---
CONTROL_BLINK_ENABLE_SHIFT               = 0
CONTROL_BLINK_ENABLE_MASK                = 0x1
CONTROL_DAC_ENABLE_SHIFT                 = 1
CONTROL_DAC_ENABLE_MASK                  = 0x2
CONTROL_NCO_PHASE_RESET_SHIFT            = 2
CONTROL_NCO_PHASE_RESET_MASK             = 0x4
CONTROL_PID_ENABLE_SHIFT                 = 3
CONTROL_PID_ENABLE_MASK                  = 0x8
CONTROL_LOCK_ENABLE_SHIFT                = 4
CONTROL_LOCK_ENABLE_MASK                 = 0x10
CONTROL_PID_ENABLE_B_SHIFT               = 5
CONTROL_PID_ENABLE_B_MASK                = 0x20
CONTROL_LOCK_ENABLE_B_SHIFT              = 6
CONTROL_LOCK_ENABLE_B_MASK               = 0x40
CAPTURE_CTRL_TRIGGER_SHIFT               = 0
CAPTURE_CTRL_TRIGGER_MASK                = 0x1
CAPTURE_STATUS_CAPTURE_DONE_SHIFT        = 0
CAPTURE_STATUS_CAPTURE_DONE_MASK         = 0x1
CAPTURE_STATUS_DEPTH_SHIFT               = 16
CAPTURE_STATUS_DEPTH_MASK                = 0xffff0000
BUFFER_ENABLE_ENABLE_SHIFT               = 0
BUFFER_ENABLE_ENABLE_MASK                = 0x1
PID_GAINS_KP_SHIFT                       = 16
PID_GAINS_KP_MASK                        = 0xffff0000
PID_GAINS_KI_SHIFT                       = 0
PID_GAINS_KI_MASK                        = 0xffff
PID_STATUS_SATURATED_HIGH_SHIFT          = 0
PID_STATUS_SATURATED_HIGH_MASK           = 0x1
PID_STATUS_SATURATED_LOW_SHIFT           = 1
PID_STATUS_SATURATED_LOW_MASK            = 0x2
LOCK_STATUS_LOCKED_SHIFT                 = 0
LOCK_STATUS_LOCKED_MASK                  = 0x1
SYNC_CONTROL_SYNC_MASTER_ENABLE_SHIFT    = 0
SYNC_CONTROL_SYNC_MASTER_ENABLE_MASK     = 0x1
SYNC_CONTROL_SYNC_SLAVE_ENABLE_SHIFT     = 1
SYNC_CONTROL_SYNC_SLAVE_ENABLE_MASK      = 0x2
SYNC_CONTROL_SYNC_RETRANSMIT_ENABLE_SHIFT = 2
SYNC_CONTROL_SYNC_RETRANSMIT_ENABLE_MASK = 0x4
ADC_SELECT_RAW_ADC_SELECT_SHIFT          = 0
ADC_SELECT_RAW_ADC_SELECT_MASK           = 0x1
ADC_SELECT_DEC_ADC_SELECT_SHIFT          = 1
ADC_SELECT_DEC_ADC_SELECT_MASK           = 0x2
PID_GAINS_B_KP_SHIFT                     = 16
PID_GAINS_B_KP_MASK                      = 0xffff0000
PID_GAINS_B_KI_SHIFT                     = 0
PID_GAINS_B_KI_MASK                      = 0xffff
PID_STATUS_B_SATURATED_HIGH_SHIFT        = 0
PID_STATUS_B_SATURATED_HIGH_MASK         = 0x1
PID_STATUS_B_SATURATED_LOW_SHIFT         = 1
PID_STATUS_B_SATURATED_LOW_MASK          = 0x2
LOCK_STATUS_B_LOCKED_SHIFT               = 0
LOCK_STATUS_B_LOCKED_MASK                = 0x1

# --- introspectable metadata ---
REGISTERS = {
    'control': {'offset': 0x00, 'access': 'rw', 'reset': 0x1,
        'source': 'n/a', 'fields': {'blink_enable': (0x1, 0), 'dac_enable': (0x2, 1), 'nco_phase_reset': (0x4, 2), 'pid_enable': (0x8, 3), 'lock_enable': (0x10, 4), 'pid_enable_b': (0x20, 5), 'lock_enable_b': (0x40, 6)},
        'description': 'axis-A: bit0 blink_enable, bit1 dac_enable, bit2 nco_phase_reset, bit3 pid_enable, bit4 lock_enable. axis-B: bit5 pid_enable_B, bit6 lock_enable_B.'},
    'blink_half_period': {'offset': 0x04, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'LED blink half-period in clk cycles (0 -> default 62.5M = 1 Hz).'},
    'scratch': {'offset': 0x08, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Software round-trip test register.'},
    'magic': {'offset': 0x0c, 'access': 'ro', 'reset': 0xdeadbeef,
        'source': 'const', 'fields': {},
        'description': 'Bridge sanity constant.'},
    'nco_tuning_word': {'offset': 0x10, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'f_DAC = tuning_word * 125 MHz / 2^32.'},
    'nco_amplitude': {'offset': 0x14, 'access': 'rw', 'reset': 0x3fff,
        'source': 'n/a', 'fields': {},
        'description': '14-bit unsigned, full-scale at 0x3FFF.'},
    'capture_ctrl': {'offset': 0x18, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'trigger': (0x1, 0)},
        'description': 'bit 0 = trigger an 8K-sample raw ADC capture.'},
    'capture_status': {'offset': 0x1c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {'capture_done': (0x1, 0), 'depth': (0xffff0000, 16)},
        'description': 'bit 0 capture_done, bits [31:16] = depth (8192).'},
    'freq_gate_cycles': {'offset': 0x20, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'freq counter gate window in clk cycles (0 -> default 125_000 = 1 ms).'},
    'freq_count_raw': {'offset': 0x24, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched zero-crossing count, raw-ADC path.'},
    'freq_threshold': {'offset': 0x28, 'access': 'rw', 'reset': 0x32,
        'source': 'n/a', 'fields': {},
        'description': 'Schmitt hysteresis half-band (16-bit signed, default 50).'},
    'freq_count_dec': {'offset': 0x2c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched zero-crossing count, CIC+FIR path.'},
    'amp_raw': {'offset': 0x30, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Peak |sample| over gate, raw-ADC path.'},
    'amp_dec': {'offset': 0x34, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Peak |sample| over gate, CIC+FIR path.'},
    'buffer_enable': {'offset': 0x38, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'enable': (0x1, 0)},
        'description': 'bit 0 = stream records into the circular buffer each gate.'},
    'buffer_write_ptr': {'offset': 0x3c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Next slot the FPGA will write (0..depth-1).'},
    'buffer_sample_count': {'offset': 0x40, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Monotonic total writes since enable.'},
    'buffer_depth': {'offset': 0x44, 'access': 'ro', 'reset': 0x400,
        'source': 'const', 'fields': {},
        'description': 'Buffer depth in records (constant from PL param, 1024).'},
    'pid_setpoint': {'offset': 0x48, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'PID setpoint in freq-counter counts (signed).'},
    'pid_gains': {'offset': 0x4c, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'kp': (0xffff0000, 16), 'ki': (0xffff, 0)},
        'description': '[31:16] = kp, [15:0] = ki (both Q4.12 signed).'},
    'nco_shift': {'offset': 0x50, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Left-shift applied to PID output before adding to base_tw.'},
    'pid_output': {'offset': 0x54, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latest PID controller output (signed).'},
    'pid_status': {'offset': 0x58, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {'saturated_high': (0x1, 0), 'saturated_low': (0x2, 1)},
        'description': 'bit 0 saturated_high, bit 1 saturated_low.'},
    'lock_status': {'offset': 0x5c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {'locked': (0x1, 0)},
        'description': 'bit 0 = locked (state machine output).'},
    'lock_target_tw': {'offset': 0x60, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'NCO tuning word the ramp aims at.'},
    'lock_ramp_rate': {'offset': 0x64, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'tuning-word units per gate pulse during ramp.'},
    'lock_capture_win': {'offset': 0x68, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'freq-counter error threshold (counts) to declare lock early.'},
    'sync_control': {'offset': 0x6c, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'sync_master_enable': (0x1, 0), 'sync_slave_enable': (0x2, 1), 'sync_retransmit_enable': (0x4, 2)},
        'description': 'multi-board trigger sync (Path A). Default 0 is invisible.'},
    'adc_select': {'offset': 0x70, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'raw_adc_select': (0x1, 0), 'dec_adc_select': (0x2, 1)},
        'description': 'ADC channel selector for the on-PL freq counters.'},
    'nco_tuning_word_b': {'offset': 0x74, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'axis-B NCO phase increment.'},
    'nco_amplitude_b': {'offset': 0x78, 'access': 'rw', 'reset': 0x3fff,
        'source': 'n/a', 'fields': {},
        'description': 'axis-B NCO amplitude (14-bit unsigned).'},
    'freq_count_dec_b': {'offset': 0x7c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'axis-B decimated zero-crossing count.'},
    'amp_dec_b': {'offset': 0x80, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'axis-B decimated peak amplitude.'},
    'pid_setpoint_b': {'offset': 0x84, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'axis-B PID setpoint (counts).'},
    'pid_gains_b': {'offset': 0x88, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'kp': (0xffff0000, 16), 'ki': (0xffff, 0)},
        'description': 'axis-B [31:16] = kp_B, [15:0] = ki_B (Q4.12 signed).'},
    'nco_shift_b': {'offset': 0x8c, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'axis-B PID-out left-shift before nco_summer.'},
    'pid_output_b': {'offset': 0x90, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': "axis-B PID's latest control output."},
    'pid_status_b': {'offset': 0x94, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {'saturated_high': (0x1, 0), 'saturated_low': (0x2, 1)},
        'description': 'bit 0 saturated_high_B, bit 1 saturated_low_B.'},
    'lock_status_b': {'offset': 0x98, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {'locked': (0x1, 0)},
        'description': 'bit 0 = locked_B.'},
    'lock_target_tw_b': {'offset': 0x9c, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'axis-B lock-acquisition ramp target.'},
    'lock_ramp_rate_b': {'offset': 0xa0, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'axis-B lock ramp rate per gate.'},
    'lock_capture_win_b': {'offset': 0xa4, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'axis-B lock capture window.'},
}

# Convenience groupings.
WRITABLE = [n for n, m in REGISTERS.items() if m['access'] == 'rw']
READABLE = list(REGISTERS.keys())


def get_field(word, shift, mask):
    """Extract a bitfield value from a full register word."""
    return (word & mask) >> shift


def set_field(word, shift, mask, value):
    """Return `word` with the masked bitfield replaced by `value`."""
    return (word & ~mask) | ((value << shift) & mask)
