"""AUTO-GENERATED by regspec/generators/gen_python.py — DO NOT EDIT BY HAND.

Register map for 'core' (26 registers).
Regenerate with: python regspec/gen_all.py <spec>.yaml
"""

BASE_ADDRESS = 0x40000000
DATA_WIDTH = 32
ADDR_SPAN = 0x80

# --- register offsets (bytes from BASE_ADDRESS) ---
REG_CONTROL                      = 0x00
REG_MAGIC                        = 0x04
REG_SCRATCH                      = 0x08
REG_GATE_CYCLES                  = 0x0c
REG_THRESHOLD                    = 0x10
REG_BUFFER_ENABLE                = 0x14
REG_BUFFER_WRITE_PTR             = 0x18
REG_BUFFER_SAMPLE_COUNT          = 0x1c
REG_BUFFER_DEPTH                 = 0x20
REG_SYNC_CONTROL                 = 0x24
REG_NCO_TUNING_WORD_CH0          = 0x28
REG_NCO_AMPLITUDE_CH0            = 0x2c
REG_PID_SETPOINT_CH0             = 0x30
REG_PID_GAINS_CH0                = 0x34
REG_PID_OUTPUT_CH0               = 0x38
REG_LOCK_STATUS_CH0              = 0x3c
REG_MEAS_COUNT_CH0               = 0x40
REG_MEAS_AMP_CH0                 = 0x44
REG_NCO_TUNING_WORD_CH1          = 0x48
REG_NCO_AMPLITUDE_CH1            = 0x4c
REG_PID_SETPOINT_CH1             = 0x50
REG_PID_GAINS_CH1                = 0x54
REG_PID_OUTPUT_CH1               = 0x58
REG_LOCK_STATUS_CH1              = 0x5c
REG_MEAS_COUNT_CH1               = 0x60
REG_MEAS_AMP_CH1                 = 0x64

# --- bitfields: (shift, mask) per field ---
CONTROL_SYS_ENABLE_SHIFT                 = 0
CONTROL_SYS_ENABLE_MASK                  = 0x1
CONTROL_DAC_ENABLE_SHIFT                 = 1
CONTROL_DAC_ENABLE_MASK                  = 0x2
CONTROL_PHASE_RESET_SHIFT                = 2
CONTROL_PHASE_RESET_MASK                 = 0x4
BUFFER_ENABLE_ENABLE_SHIFT               = 0
BUFFER_ENABLE_ENABLE_MASK                = 0x1
SYNC_CONTROL_MASTER_ENABLE_SHIFT         = 0
SYNC_CONTROL_MASTER_ENABLE_MASK          = 0x1
SYNC_CONTROL_SLAVE_ENABLE_SHIFT          = 1
SYNC_CONTROL_SLAVE_ENABLE_MASK           = 0x2
SYNC_CONTROL_RETRANSMIT_ENABLE_SHIFT     = 2
SYNC_CONTROL_RETRANSMIT_ENABLE_MASK      = 0x4
PID_GAINS_CH0_KP_SHIFT                   = 16
PID_GAINS_CH0_KP_MASK                    = 0xffff0000
PID_GAINS_CH0_KI_SHIFT                   = 0
PID_GAINS_CH0_KI_MASK                    = 0xffff
PID_GAINS_CH1_KP_SHIFT                   = 16
PID_GAINS_CH1_KP_MASK                    = 0xffff0000
PID_GAINS_CH1_KI_SHIFT                   = 0
PID_GAINS_CH1_KI_MASK                    = 0xffff

# --- introspectable metadata ---
REGISTERS = {
    'control': {'offset': 0x00, 'access': 'rw', 'reset': 0x1,
        'source': 'n/a', 'fields': {'sys_enable': (0x1, 0), 'dac_enable': (0x2, 1), 'phase_reset': (0x4, 2)},
        'description': 'Global control bits.'},
    'magic': {'offset': 0x04, 'access': 'ro', 'reset': 0xdeadbeef,
        'source': 'const', 'fields': {},
        'description': 'Bridge sanity constant — read to confirm the AXI link is alive.'},
    'scratch': {'offset': 0x08, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Software round-trip test register (write/read to verify the bridge).'},
    'gate_cycles': {'offset': 0x0c, 'access': 'rw', 'reset': 0x1312d0,
        'source': 'n/a', 'fields': {},
        'description': 'Measurement gate window in clk cycles (0 -> module default).'},
    'threshold': {'offset': 0x10, 'access': 'rw', 'reset': 0x32,
        'source': 'n/a', 'fields': {},
        'description': 'Measurement discriminator half-band (e.g. Schmitt hysteresis), in ADC codes.'},
    'buffer_enable': {'offset': 0x14, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'enable': (0x1, 0)},
        'description': 'bit 0 -> stream one record per gate into the circular buffer.'},
    'buffer_write_ptr': {'offset': 0x18, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Next slot the PL will write (0 .. depth-1).'},
    'buffer_sample_count': {'offset': 0x1c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Monotonic total records written since enable (lets the DAQ detect overrun).'},
    'buffer_depth': {'offset': 0x20, 'access': 'ro', 'reset': 0x400,
        'source': 'const', 'fields': {},
        'description': 'Circular-buffer depth in records (from the PL BRAM parameter).'},
    'sync_control': {'offset': 0x24, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'master_enable': (0x1, 0), 'slave_enable': (0x2, 1), 'retransmit_enable': (0x4, 2)},
        'description': 'Multi-board trigger sync (Path A) over the DAISY/SATA connector.'},
    'nco_tuning_word_ch0': {'offset': 0x28, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'NCO phase increment. f_out = tuning_word * 125e6 / 2^32.'},
    'nco_amplitude_ch0': {'offset': 0x2c, 'access': 'rw', 'reset': 0x3fff,
        'source': 'n/a', 'fields': {},
        'description': 'NCO output amplitude (14-bit unsigned, full-scale 0x3FFF).'},
    'pid_setpoint_ch0': {'offset': 0x30, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Feedback setpoint, in measurement counts (signed).'},
    'pid_gains_ch0': {'offset': 0x34, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'kp': (0xffff0000, 16), 'ki': (0xffff, 0)},
        'description': '[31:16] = kp, [15:0] = ki (Q4.12 signed).'},
    'pid_output_ch0': {'offset': 0x38, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latest PID controller output (signed correction to the NCO word).'},
    'lock_status_ch0': {'offset': 0x3c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'bit 0 = locked (lock-acquisition state-machine output).'},
    'meas_count_ch0': {'offset': 0x40, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched measurement count for this channel (the error-signal source).'},
    'meas_amp_ch0': {'offset': 0x44, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched measurement amplitude for this channel.'},
    'nco_tuning_word_ch1': {'offset': 0x48, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'NCO phase increment. f_out = tuning_word * 125e6 / 2^32.'},
    'nco_amplitude_ch1': {'offset': 0x4c, 'access': 'rw', 'reset': 0x3fff,
        'source': 'n/a', 'fields': {},
        'description': 'NCO output amplitude (14-bit unsigned, full-scale 0x3FFF).'},
    'pid_setpoint_ch1': {'offset': 0x50, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Feedback setpoint, in measurement counts (signed).'},
    'pid_gains_ch1': {'offset': 0x54, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'kp': (0xffff0000, 16), 'ki': (0xffff, 0)},
        'description': '[31:16] = kp, [15:0] = ki (Q4.12 signed).'},
    'pid_output_ch1': {'offset': 0x58, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latest PID controller output (signed correction to the NCO word).'},
    'lock_status_ch1': {'offset': 0x5c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'bit 0 = locked (lock-acquisition state-machine output).'},
    'meas_count_ch1': {'offset': 0x60, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched measurement count for this channel (the error-signal source).'},
    'meas_amp_ch1': {'offset': 0x64, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched measurement amplitude for this channel.'},
}

# Convenience groupings.
WRITABLE = [n for n, m in REGISTERS.items() if m['access'] == 'rw']
READABLE = list(REGISTERS.keys())


def get_field(word, shift, mask):
    """Extract a bitfield value from a full register word."""
    return (word & mask) >> shift


def set_field(word, shift, mask, value):
    """Return `word` with the masked bitfield replaced by `value`."""
    return (word & ~mask) | ((value << shift) & mask)
