"""AUTO-GENERATED by regspec/generators/gen_python.py — DO NOT EDIT BY HAND.

Register map for 'nanosphere' (36 registers).
Regenerate with: python regspec/gen_all.py <spec>.yaml
"""

BASE_ADDRESS = 0x40000000
DATA_WIDTH = 32
ADDR_SPAN = 0x100

# --- register offsets (bytes from BASE_ADDRESS) ---
REG_CONTROL                      = 0x00
REG_MAGIC                        = 0x04
REG_SCRATCH                      = 0x08
REG_GATE_CYCLES                  = 0x0c
REG_THRESHOLD                    = 0x10
REG_BUFFER_ENABLE                = 0x14
REG_BUFFER_WRITE_PTR             = 0x18
REG_BUFFER_SAMPLE_COUNT          = 0x1c
REG_BUFFER_DEPTH                 = 0x20
REG_LOCKIN_REF_TW_0              = 0x24
REG_DRIVE_AMPLITUDE_0            = 0x28
REG_PID_SETPOINT_0               = 0x2c
REG_PID_GAINS_0                  = 0x30
REG_PID_OUTPUT_0                 = 0x34
REG_LOCK_STATUS_0                = 0x38
REG_MEAS_MAG_0                   = 0x3c
REG_MEAS_I_0                     = 0x40
REG_MEAS_Q_0                     = 0x44
REG_LOCKIN_REF_TW_1              = 0x48
REG_DRIVE_AMPLITUDE_1            = 0x4c
REG_PID_SETPOINT_1               = 0x50
REG_PID_GAINS_1                  = 0x54
REG_PID_OUTPUT_1                 = 0x58
REG_LOCK_STATUS_1                = 0x5c
REG_MEAS_MAG_1                   = 0x60
REG_MEAS_I_1                     = 0x64
REG_MEAS_Q_1                     = 0x68
REG_LOCKIN_REF_TW_2              = 0x6c
REG_DRIVE_AMPLITUDE_2            = 0x70
REG_PID_SETPOINT_2               = 0x74
REG_PID_GAINS_2                  = 0x78
REG_PID_OUTPUT_2                 = 0x7c
REG_LOCK_STATUS_2                = 0x80
REG_MEAS_MAG_2                   = 0x84
REG_MEAS_I_2                     = 0x88
REG_MEAS_Q_2                     = 0x8c

# --- bitfields: (shift, mask) per field ---
CONTROL_SYS_ENABLE_SHIFT                 = 0
CONTROL_SYS_ENABLE_MASK                  = 0x1
CONTROL_DAC_ENABLE_SHIFT                 = 1
CONTROL_DAC_ENABLE_MASK                  = 0x2
CONTROL_PHASE_RESET_SHIFT                = 2
CONTROL_PHASE_RESET_MASK                 = 0x4
BUFFER_ENABLE_ENABLE_SHIFT               = 0
BUFFER_ENABLE_ENABLE_MASK                = 0x1
PID_GAINS_0_KP_SHIFT                     = 16
PID_GAINS_0_KP_MASK                      = 0xffff0000
PID_GAINS_0_KI_SHIFT                     = 0
PID_GAINS_0_KI_MASK                      = 0xffff
PID_GAINS_1_KP_SHIFT                     = 16
PID_GAINS_1_KP_MASK                      = 0xffff0000
PID_GAINS_1_KI_SHIFT                     = 0
PID_GAINS_1_KI_MASK                      = 0xffff
PID_GAINS_2_KP_SHIFT                     = 16
PID_GAINS_2_KP_MASK                      = 0xffff0000
PID_GAINS_2_KI_SHIFT                     = 0
PID_GAINS_2_KI_MASK                      = 0xffff

# --- introspectable metadata ---
REGISTERS = {
    'control': {'offset': 0x00, 'access': 'rw', 'reset': 0x1,
        'source': 'n/a', 'fields': {'sys_enable': (0x1, 0), 'dac_enable': (0x2, 1), 'phase_reset': (0x4, 2)},
        'description': 'Global control bits.'},
    'magic': {'offset': 0x04, 'access': 'ro', 'reset': 0xdeadbeef,
        'source': 'const', 'fields': {},
        'description': 'Bridge sanity constant.'},
    'scratch': {'offset': 0x08, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Software round-trip test register.'},
    'gate_cycles': {'offset': 0x0c, 'access': 'rw', 'reset': 0x1312d0,
        'source': 'n/a', 'fields': {},
        'description': 'Lock-in integration window in clk cycles (10 ms at 125 MHz).'},
    'threshold': {'offset': 0x10, 'access': 'rw', 'reset': 0x32,
        'source': 'n/a', 'fields': {},
        'description': 'Amplitude/sensitivity discriminator (codes).'},
    'buffer_enable': {'offset': 0x14, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'enable': (0x1, 0)},
        'description': 'bit 0 -> stream one record per gate.'},
    'buffer_write_ptr': {'offset': 0x18, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Next circular-buffer slot the PL will write.'},
    'buffer_sample_count': {'offset': 0x1c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Monotonic total records written since enable.'},
    'buffer_depth': {'offset': 0x20, 'access': 'ro', 'reset': 0x400,
        'source': 'const', 'fields': {},
        'description': 'Circular-buffer depth in records.'},
    'lockin_ref_tw_0': {'offset': 0x24, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Reference-oscillator phase increment (mechanical mode frequency).'},
    'drive_amplitude_0': {'offset': 0x28, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Feedback drive amplitude scale (14-bit unsigned).'},
    'pid_setpoint_0': {'offset': 0x2c, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Target for the demodulated error signal (signed). 0 = cool to zero.'},
    'pid_gains_0': {'offset': 0x30, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'kp': (0xffff0000, 16), 'ki': (0xffff, 0)},
        'description': '[31:16] = kp, [15:0] = ki (Q4.12 signed).'},
    'pid_output_0': {'offset': 0x34, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latest PID feedback output (signed).'},
    'lock_status_0': {'offset': 0x38, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'bit 0 = engaged/stable.'},
    'meas_mag_0': {'offset': 0x3c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Demodulated magnitude (lock_in error_count) for this axis — the PID error source.'},
    'meas_i_0': {'offset': 0x40, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched in-phase (I) lock-in output for this axis.'},
    'meas_q_0': {'offset': 0x44, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched quadrature (Q) lock-in output for this axis.'},
    'lockin_ref_tw_1': {'offset': 0x48, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Reference-oscillator phase increment (mechanical mode frequency).'},
    'drive_amplitude_1': {'offset': 0x4c, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Feedback drive amplitude scale (14-bit unsigned).'},
    'pid_setpoint_1': {'offset': 0x50, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Target for the demodulated error signal (signed). 0 = cool to zero.'},
    'pid_gains_1': {'offset': 0x54, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'kp': (0xffff0000, 16), 'ki': (0xffff, 0)},
        'description': '[31:16] = kp, [15:0] = ki (Q4.12 signed).'},
    'pid_output_1': {'offset': 0x58, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latest PID feedback output (signed).'},
    'lock_status_1': {'offset': 0x5c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'bit 0 = engaged/stable.'},
    'meas_mag_1': {'offset': 0x60, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Demodulated magnitude (lock_in error_count) for this axis — the PID error source.'},
    'meas_i_1': {'offset': 0x64, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched in-phase (I) lock-in output for this axis.'},
    'meas_q_1': {'offset': 0x68, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched quadrature (Q) lock-in output for this axis.'},
    'lockin_ref_tw_2': {'offset': 0x6c, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Reference-oscillator phase increment (mechanical mode frequency).'},
    'drive_amplitude_2': {'offset': 0x70, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Feedback drive amplitude scale (14-bit unsigned).'},
    'pid_setpoint_2': {'offset': 0x74, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {},
        'description': 'Target for the demodulated error signal (signed). 0 = cool to zero.'},
    'pid_gains_2': {'offset': 0x78, 'access': 'rw', 'reset': 0x0,
        'source': 'n/a', 'fields': {'kp': (0xffff0000, 16), 'ki': (0xffff, 0)},
        'description': '[31:16] = kp, [15:0] = ki (Q4.12 signed).'},
    'pid_output_2': {'offset': 0x7c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latest PID feedback output (signed).'},
    'lock_status_2': {'offset': 0x80, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'bit 0 = engaged/stable.'},
    'meas_mag_2': {'offset': 0x84, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Demodulated magnitude (lock_in error_count) for this axis — the PID error source.'},
    'meas_i_2': {'offset': 0x88, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched in-phase (I) lock-in output for this axis.'},
    'meas_q_2': {'offset': 0x8c, 'access': 'ro', 'reset': 0x0,
        'source': 'input', 'fields': {},
        'description': 'Latched quadrature (Q) lock-in output for this axis.'},
}

# Convenience groupings.
WRITABLE = [n for n, m in REGISTERS.items() if m['access'] == 'rw']
READABLE = list(REGISTERS.keys())


def get_field(word, shift, mask):
    """Extract a bitfield value from a full register word."""
    return (word & mask) >> shift


def set_field(word, shift, mask, value):
    """Return `word` with the masked bitfield replaced by `value`."""
    return (word & ~mask) | ((value << shift) & mask)
