# ============================================================================
# drc_gen2.tcl — Vivado DRC harness for the WP-SYNC Gen-2 sync retarget
# ============================================================================
# GATED — run on the device machine only. From the framework repo root:
#
#     vivado -mode batch -source fpga/drc_gen2.tcl
#
# What it does: builds a throwaway xc7z020clg400-1 (STEMlab 65-16 TI, Gen 2)
# project, synthesizes a small stub top that instantiates the RETARGETED
# rtl/infra/sync_io.v (real IBUFDS/OBUFDS — no -DSIM) and exercises every port
# the board XDC constrains — including the full Z20_ll two-pair daisy buses
# (daisy_p/n_o[1:0], daisy_p/n_i[1:0]) — applies the RETARGETED
# constraints/red_pitaya.xdc, and runs report_drc. It prints a violation
# breakdown and exits NON-ZERO if any DRC violation of severity "Error" remains
# — i.e. it proves the retargeted XDC + IBUFDS/OBUFDS IOSTANDARD (DIFF_SSTL18_I)
# are FPGA-internally legal on the xc7z020.
#
# This validates FPGA-INTERNAL legality only: valid clg400 pins, legal
# differential pairs, consistent bank VCCO vs IOSTANDARD, buffered diff I/O,
# valid false_path. It does NOT (cannot) validate that a pin physically reaches
# the second board — see the hardware-gate note below.
#
# ── HARDWARE-GATE NOTE (Batch 2 — Decision D-A2; NOT this package) ───────────
# The retargeted XDC ASSUMES the *X-channel 2.0 Click Shield* two-board sync path
# (shared oscillator, works out-of-the-box) as the default bring-up route, rather
# than *direct S1/S2 cabling* (which may require a secondary-board hardware mod).
# The daisy pin LOCs in constraints/red_pitaya.xdc are the bench-verified Red
# Pitaya daisy differential pairs on the clg400 package (guaranteed-valid diff
# pairs, so this DRC is clean either way); WHICH physical route is used, and the
# exact 65-16 TI board-file LOCs for that route, are confirmed at Batch-2 hardware
# bring-up, not here. If the direct-S1/S2 route is chosen at that gate, re-confirm
# the daisy LOCs against the 65-16 TI board file and re-run this DRC.
# ============================================================================

set part          "xc7z020clg400-1"
set script_dir    [file dirname [file normalize [info script]]]
set repo_root     [file dirname $script_dir]
set sync_v        [file join $repo_root rtl infra sync_io.v]
set board_xdc     [file join $repo_root constraints red_pitaya.xdc]
set work_dir      [file join $script_dir .drc_gen2_work]
set stub_v        [file join $work_dir drc_stub_top.v]
set drc_rpt       [file join $work_dir drc_report.txt]

foreach f [list $sync_v $board_xdc] {
    if {![file exists $f]} { puts "ERROR: missing input: $f"; exit 2 }
}

file delete -force $work_dir
file mkdir $work_dir

# --- Stub top: exercises every port the board XDC constrains so nothing is
#     trimmed (no unbuffered-diff / no-driver DRCs), and wires the full two-pair
#     daisy buses through the real sync_io (real IBUFDS/OBUFDS). sync_io buffers
#     TX pairs [0]+[1] and RX pair [0]; the reserved RX pair [1] (DAISY_IO3) is
#     not consumed by sync_io, so the stub buffers it here (a single IBUFDS on
#     that pin — no double-buffer) to keep the constrained port legal. ---
set fh [open $stub_v w]
puts $fh {`timescale 1ns / 1ps
// Auto-generated by fpga/drc_gen2.tcl — DRC-only stub, not a real design.
module drc_stub_top (
    input  wire        adc_clk_p,
    input  wire        adc_clk_n,
    input  wire [13:0] adc_dat_a,
    input  wire [13:0] adc_dat_b,
    output wire [13:0] dac_dat,
    output wire        dac_wrt,
    output wire        dac_sel,
    output wire        dac_clk_o,
    output wire        dac_rst,
    output wire [1:0]  daisy_p_o,
    output wire [1:0]  daisy_n_o,
    input  wire [1:0]  daisy_p_i,
    input  wire [1:0]  daisy_n_i,
    output wire [7:0]  led_o
);
    wire clk;
    IBUFDS ibufds_adc_clk (.I(adc_clk_p), .IB(adc_clk_n), .O(clk));

    wire sync_reset;
    sync_io u_sync (
        .clk                    (clk),
        .rst_n                  (1'b1),
        .sync_master_enable     (adc_dat_a[0]),
        .sync_slave_enable      (adc_dat_a[1]),
        .sync_retransmit_enable (adc_dat_a[2]),
        .master_pulse           (adc_dat_a[3]),
        .daisy_p_o              (daisy_p_o),
        .daisy_n_o              (daisy_n_o),
        .daisy_p_i              (daisy_p_i),
        .daisy_n_i              (daisy_n_i),
        .sync_reset             (sync_reset)
    );

    // Reserved RX pair [1] (DAISY_IO3) — buffered here since sync_io leaves it
    // unused; keeps the constrained input port legal for DRC.
    wire daisy_rx_rsvd;
    IBUFDS #(.IOSTANDARD("DIFF_SSTL18_I")) ibufds_daisy_rsvd (
        .I  (daisy_p_i[1]),
        .IB (daisy_n_i[1]),
        .O  (daisy_rx_rsvd)
    );

    // Trivial clocked logic so every remaining port is kept and buffered.
    reg [13:0] r_dac = 14'd0;
    reg [7:0]  r_led = 8'd0;
    reg        r_wrt = 1'b0, r_sel = 1'b0, r_clk = 1'b0, r_rst = 1'b0;
    always @(posedge clk) begin
        r_dac <= adc_dat_b ^ {14{sync_reset}};
        r_led <= adc_dat_a[7:0] ^ {8{sync_reset}} ^ {8{daisy_rx_rsvd}};
        r_wrt <= adc_dat_b[0];
        r_sel <= adc_dat_b[1];
        r_clk <= adc_dat_b[2];
        r_rst <= adc_dat_b[3];
    end
    assign dac_dat   = r_dac;
    assign led_o     = r_led;
    assign dac_wrt   = r_wrt;
    assign dac_sel   = r_sel;
    assign dac_clk_o = r_clk;
    assign dac_rst   = r_rst;
endmodule}
close $fh

# --- Build ---
create_project -in_memory -part $part
read_verilog $sync_v
read_verilog $stub_v
read_xdc     $board_xdc

# synth_design (real IBUFDS/OBUFDS: sync_io's `ifdef SIM is NOT defined here).
synth_design -top drc_stub_top -part $part

# --- DRC ---
report_drc -file $drc_rpt
puts "\n==== DRC report written to $drc_rpt ===="

set n_error 0
set n_crit  0
set n_warn  0
foreach v [get_drc_violations] {
    set sev [get_property SEVERITY $v]
    switch -exact -- $sev {
        "Error"            { incr n_error }
        "Critical Warning" { incr n_crit  }
        "Warning"          { incr n_warn  }
    }
}

puts "==== DRC summary: $n_error error(s), $n_crit critical warning(s), $n_warn warning(s) ===="
if {$n_error > 0} {
    puts "==== FAIL: DRC reported $n_error error(s) for $part with the retargeted XDC ===="
    foreach v [get_drc_violations -filter {SEVERITY == "Error"}] {
        puts "  \[[get_property RULE $v]\] $v: [get_property DESCRIPTION $v]"
    }
    exit 1
}

puts "==== PASS: 0 DRC errors for $part with the retargeted S1/S2 daisy XDC ===="
puts "==== (review the $n_crit critical warning(s) / $n_warn warning(s) in $drc_rpt) ===="
exit 0
