"""Generate a host/board Python register module from a RegSpec.

Output is plain, dependency-free Python compatible with the Red Pitaya's
on-board Python 3.5: register offset constants, per-field shift/mask constants,
an introspectable REGISTERS metadata dict, and tiny get/set-field helpers. This
is what replaces the hand-maintained REG_* block in board_io.py.
"""

from __future__ import annotations


def _up(name: str) -> str:
    return name.upper()


def generate(spec) -> str:
    L = []
    ap = L.append
    ap('"""AUTO-GENERATED by regspec/generators/gen_python.py — DO NOT EDIT BY HAND.')
    ap("")
    ap("Register map for '{}' ({} registers).".format(spec.name, len(spec.registers)))
    ap("Regenerate with: python regspec/gen_all.py <spec>.yaml")
    ap('"""')
    ap("")
    ap("BASE_ADDRESS = 0x{:08x}".format(spec.base_address))
    ap("DATA_WIDTH = {}".format(spec.data_width))
    ap("ADDR_SPAN = 0x{:x}".format(spec.addr_span))
    ap("")
    ap("# --- register offsets (bytes from BASE_ADDRESS) ---")
    for r in spec.registers:
        ap("REG_{:<28s} = 0x{:02x}".format(_up(r.name), r.offset))
    ap("")

    # Field shift/mask constants.
    any_fields = any(r.fields for r in spec.registers)
    if any_fields:
        ap("# --- bitfields: (shift, mask) per field ---")
        for r in spec.registers:
            for f in r.fields:
                pfx = "{}_{}".format(_up(r.name), _up(f.name))
                ap("{:<40s} = {}".format(pfx + "_SHIFT", f.lsb))
                ap("{:<40s} = 0x{:x}".format(pfx + "_MASK", f.mask))
        ap("")

    # Metadata dict for introspection / generic tooling.
    ap("# --- introspectable metadata ---")
    ap("REGISTERS = {")
    for r in spec.registers:
        fields_repr = "{" + ", ".join(
            "'{}': (0x{:x}, {})".format(f.name, f.mask, f.lsb) for f in r.fields
        ) + "}"
        ap("    '{}': {{'offset': 0x{:02x}, 'access': '{}', 'reset': 0x{:x},".format(
            r.name, r.offset, r.access, r.reset))
        ap("        'source': '{}', 'fields': {},".format(r.source, fields_repr))
        ap("        'description': {!r}}},".format(r.description))
    ap("}")
    ap("")
    ap("# Convenience groupings.")
    ap("WRITABLE = [n for n, m in REGISTERS.items() if m['access'] == 'rw']")
    ap("READABLE = list(REGISTERS.keys())")
    ap("")
    ap("")
    ap("def get_field(word, shift, mask):")
    ap('    """Extract a bitfield value from a full register word."""')
    ap("    return (word & mask) >> shift")
    ap("")
    ap("")
    ap("def set_field(word, shift, mask, value):")
    ap('    """Return `word` with the masked bitfield replaced by `value`."""')
    ap("    return (word & ~mask) | ((value << shift) & mask)")
    ap("")
    return "\n".join(L)
