"""Generate a Markdown register-map table from a RegSpec.

This is the human-facing documentation artifact — the same table people used to
maintain by hand in implementation_status.md, now generated so it can never
drift from the Verilog or the Python.
"""

from __future__ import annotations


def _fields_cell(reg) -> str:
    if not reg.fields:
        return ""
    parts = []
    for f in reg.fields:
        bits = "[{}]".format(f.lsb) if f.lsb == f.msb else "[{}:{}]".format(f.msb, f.lsb)
        label = "{} {}".format(bits, f.name)
        if f.description:
            label += " ({})".format(f.description)
        parts.append(label)
    return "; ".join(parts)


def generate(spec) -> str:
    L = []
    ap = L.append
    ap("<!-- AUTO-GENERATED by regspec/generators/gen_docs.py — DO NOT EDIT BY HAND. -->")
    ap("# Register map — {}".format(spec.name))
    ap("")
    if spec.description:
        ap(spec.description)
        ap("")
    ap("- Base address: `0x{:08x}`".format(spec.base_address))
    ap("- Data width: {} bits".format(spec.data_width))
    ap("- Address span: `0x{:x}` bytes ({} address bits)".format(
        spec.addr_span, spec.addr_width))
    ap("- Registers: {}".format(len(spec.registers)))
    ap("")
    ap("| Offset | Name | Access | Reset | Fields | Description |")
    ap("|--------|------|--------|-------|--------|-------------|")
    for r in spec.registers:
        acc = r.access
        if r.is_input:
            acc += " (in)"
        elif r.is_const:
            acc += " (const)"
        ap("| `0x{:02x}` | `{}` | {} | `0x{:x}` | {} | {} |".format(
            r.offset, r.name, acc, r.reset, _fields_cell(r), r.description))
    ap("")
    return "\n".join(L)
