"""Generate a synthesizable AXI4-Lite slave register file from a RegSpec.

The emitted module mirrors the hand-written axi_lite_slave.v pattern used in the
spin-controller, but is produced entirely from the spec:

  * every `rw` register -> a storage reg (WSTRB byte-enabled), reset to its
    `reset` value, exposed to the PL as an output port `<name>_o`;
  * every `ro`/input register -> an input port `<name>_i` that the read path
    returns (the PL drives it — measurements, status, counts);
  * every `ro`/const register -> the read path returns its `reset` constant
    (bridge sanity words like 0xDEADBEEF, depth parameters, ...).

Single clock domain (the AXI ACLK, which on Red Pitaya is the 125 MHz fabric
clock). Standard AXI4-Lite handshake; no wait states.
"""

from __future__ import annotations


def _clog2(n: int) -> int:
    return max(1, (n - 1).bit_length())


def _port_lines(spec) -> list:
    w = spec.data_width
    lines = []
    for r in spec.registers:
        if r.access == "rw":
            lines.append("    output wire [{}:0] {}_o,".format(w - 1, r.name))
        elif r.is_input:
            lines.append("    input  wire [{}:0] {}_i,".format(w - 1, r.name))
    return lines


def generate(spec) -> str:
    w = spec.data_width
    addr_w = spec.addr_width
    addr_lsb = _clog2(spec.word_bytes)
    idx_hi = addr_w - 1
    strb_bytes = spec.word_bytes

    def idx(r):
        return r.offset >> addr_lsb

    L = []
    ap = L.append
    ap("// AUTO-GENERATED by regspec/generators/gen_verilog.py — DO NOT EDIT BY HAND.")
    ap("// Source spec: {} ({} registers).".format(spec.name, len(spec.registers)))
    ap("// Regenerate with: python regspec/gen_all.py <spec>.yaml")
    ap("`timescale 1ns / 1ps")
    ap("")
    ap("module {}_regs #(".format(spec.name))
    ap("    parameter integer ADDR_WIDTH = {},".format(addr_w))
    ap("    parameter integer DATA_WIDTH = {}".format(w))
    ap(")(")
    ap("    // --- design-side register I/O ---")
    for line in _port_lines(spec):
        ap(line)
    ap("")
    ap("    // --- AXI4-Lite slave interface ---")
    ap("    input  wire                     S_AXI_ACLK,")
    ap("    input  wire                     S_AXI_ARESETN,")
    ap("    input  wire [ADDR_WIDTH-1:0]    S_AXI_AWADDR,")
    ap("    input  wire                     S_AXI_AWVALID,")
    ap("    output wire                     S_AXI_AWREADY,")
    ap("    input  wire [DATA_WIDTH-1:0]    S_AXI_WDATA,")
    ap("    input  wire [(DATA_WIDTH/8)-1:0] S_AXI_WSTRB,")
    ap("    input  wire                     S_AXI_WVALID,")
    ap("    output wire                     S_AXI_WREADY,")
    ap("    output wire [1:0]               S_AXI_BRESP,")
    ap("    output wire                     S_AXI_BVALID,")
    ap("    input  wire                     S_AXI_BREADY,")
    ap("    input  wire [ADDR_WIDTH-1:0]    S_AXI_ARADDR,")
    ap("    input  wire                     S_AXI_ARVALID,")
    ap("    output wire                     S_AXI_ARREADY,")
    ap("    output wire [DATA_WIDTH-1:0]    S_AXI_RDATA,")
    ap("    output wire [1:0]               S_AXI_RRESP,")
    ap("    output wire                     S_AXI_RVALID,")
    ap("    input  wire                     S_AXI_RREADY")
    ap(");")
    ap("")
    ap("    localparam integer ADDR_LSB = {};".format(addr_lsb))
    ap("")
    ap("    reg [ADDR_WIDTH-1:0] axi_awaddr;")
    ap("    reg                  axi_awready;")
    ap("    reg                  axi_wready;")
    ap("    reg [1:0]            axi_bresp;")
    ap("    reg                  axi_bvalid;")
    ap("    reg [ADDR_WIDTH-1:0] axi_araddr;")
    ap("    reg                  axi_arready;")
    ap("    reg [DATA_WIDTH-1:0] axi_rdata;")
    ap("    reg [1:0]            axi_rresp;")
    ap("    reg                  axi_rvalid;")
    ap("")
    ap("    assign S_AXI_AWREADY = axi_awready;")
    ap("    assign S_AXI_WREADY  = axi_wready;")
    ap("    assign S_AXI_BRESP   = axi_bresp;")
    ap("    assign S_AXI_BVALID  = axi_bvalid;")
    ap("    assign S_AXI_ARREADY = axi_arready;")
    ap("    assign S_AXI_RDATA   = axi_rdata;")
    ap("    assign S_AXI_RRESP   = axi_rresp;")
    ap("    assign S_AXI_RVALID  = axi_rvalid;")
    ap("")

    # Storage registers for rw regs.
    rw_regs = [r for r in spec.registers if r.access == "rw"]
    ap("    // --- storage registers (rw) ---")
    for r in rw_regs:
        ap("    reg [DATA_WIDTH-1:0] {}_reg;".format(r.name))
    ap("")
    for r in rw_regs:
        ap("    assign {0}_o = {0}_reg;".format(r.name))
    ap("")

    # Write-address / write-data handshake.
    ap("    wire slv_wren = axi_wready & S_AXI_WVALID & axi_awready & S_AXI_AWVALID;")
    ap("")
    ap("    always @(posedge S_AXI_ACLK) begin")
    ap("        if (!S_AXI_ARESETN) begin")
    ap("            axi_awready <= 1'b0; axi_wready <= 1'b0;")
    ap("            axi_awaddr  <= 0;")
    ap("        end else begin")
    ap("            if (!axi_awready && S_AXI_AWVALID && S_AXI_WVALID) begin")
    ap("                axi_awready <= 1'b1; axi_awaddr <= S_AXI_AWADDR;")
    ap("            end else axi_awready <= 1'b0;")
    ap("            if (!axi_wready && S_AXI_WVALID && S_AXI_AWVALID)")
    ap("                axi_wready <= 1'b1;")
    ap("            else axi_wready <= 1'b0;")
    ap("        end")
    ap("    end")
    ap("")

    # Register write decode (byte-enabled).
    ap("    integer bi;")
    ap("    always @(posedge S_AXI_ACLK) begin")
    ap("        if (!S_AXI_ARESETN) begin")
    for r in rw_regs:
        ap("            {}_reg <= {}'h{:x};".format(r.name, w, r.reset & ((1 << w) - 1)))
    ap("        end else if (slv_wren) begin")
    ap("            case (axi_awaddr[{}:ADDR_LSB])".format(idx_hi))
    for r in rw_regs:
        ap("                {}'d{}: for (bi=0;bi<{};bi=bi+1) if (S_AXI_WSTRB[bi])".format(
            addr_w - addr_lsb, idx(r), strb_bytes))
        ap("                    {}_reg[bi*8 +: 8] <= S_AXI_WDATA[bi*8 +: 8];".format(r.name))
    ap("                default: ;")
    ap("            endcase")
    ap("        end")
    ap("    end")
    ap("")

    # Write response.
    ap("    always @(posedge S_AXI_ACLK) begin")
    ap("        if (!S_AXI_ARESETN) begin axi_bvalid <= 1'b0; axi_bresp <= 2'b0; end")
    ap("        else if (axi_awready && S_AXI_AWVALID && axi_wready && S_AXI_WVALID && !axi_bvalid) begin")
    ap("            axi_bvalid <= 1'b1; axi_bresp <= 2'b0;")
    ap("        end else if (S_AXI_BREADY && axi_bvalid) axi_bvalid <= 1'b0;")
    ap("    end")
    ap("")

    # Read-address handshake.
    ap("    always @(posedge S_AXI_ACLK) begin")
    ap("        if (!S_AXI_ARESETN) begin axi_arready <= 1'b0; axi_araddr <= 0; end")
    ap("        else if (!axi_arready && S_AXI_ARVALID) begin")
    ap("            axi_arready <= 1'b1; axi_araddr <= S_AXI_ARADDR;")
    ap("        end else axi_arready <= 1'b0;")
    ap("    end")
    ap("")

    # Read data mux.
    ap("    always @(posedge S_AXI_ACLK) begin")
    ap("        if (!S_AXI_ARESETN) begin axi_rvalid <= 1'b0; axi_rresp <= 2'b0; end")
    ap("        else if (axi_arready && S_AXI_ARVALID && !axi_rvalid) begin")
    ap("            axi_rvalid <= 1'b1; axi_rresp <= 2'b0;")
    ap("        end else if (axi_rvalid && S_AXI_RREADY) axi_rvalid <= 1'b0;")
    ap("    end")
    ap("")
    ap("    always @(*) begin")
    ap("        case (axi_araddr[{}:ADDR_LSB])".format(idx_hi))
    for r in spec.registers:
        if r.access == "rw":
            val = "{}_reg".format(r.name)
        elif r.is_input:
            val = "{}_i".format(r.name)
        else:  # const
            val = "{}'h{:x}".format(w, r.reset & ((1 << w) - 1))
        ap("            {}'d{}: axi_rdata = {};".format(addr_w - addr_lsb, idx(r), val))
    ap("            default: axi_rdata = {}'h0;".format(w))
    ap("        endcase")
    ap("    end")
    ap("")
    ap("endmodule")
    ap("")
    return "\n".join(L)
